"""added status column to analyses table

Revision ID: 133c9e8e78f0
Revises: 9115ce03c384
Create Date: 2025-12-12 14:56:22.265700

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "133c9e8e78f0"
down_revision: Union[str, Sequence[str], None] = "9115ce03c384"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = sa.Enum("pending", "processing", "completed", "error", name="statustype", schema="timeseries")
    status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("analyses", sa.Column("status", status_enum, server_default="pending"), schema="timeseries")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyses", "status", schema="timeseries")
    op.execute("DROP TYPE IF EXISTS timeseries.statustype;")
    # ### end Alembic commands ###
