"""added status column to analyses table

Revision ID: 34f095b555d4
Revises: 9115ce03c384
Create Date: 2025-12-12 14:20:38.425042

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34f095b555d4"
down_revision: Union[str, Sequence[str], None] = "9115ce03c384"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "anomalies",
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "completed", "error", name="statustype", schema="timeseries"),
            nullable=True,
        ),
        schema="timeseries",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("anomalies", "status", schema="timeseries")
    # ### end Alembic commands ###
