"""fixed relationship between analyses and prediction in model

Revision ID: 42b57befbbfe
Revises: 3158ca6e3e73
Create Date: 2025-12-10 16:38:51.220872

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "42b57befbbfe"
down_revision: Union[str, Sequence[str], None] = "3158ca6e3e73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
