"""Initial migration

Revision ID: 7d25c94f4d1c
Revises: 128ccb94b1f5
Create Date: 2025-12-01 13:08:42.176433

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d25c94f4d1c"
down_revision: Union[str, Sequence[str], None] = "128ccb94b1f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("anomalies", sa.Column("validated", sa.Boolean(), nullable=False), schema="timeseries")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("anomalies", "validated", schema="timeseries")
    # ### end Alembic commands ###
