"""fixed relationship between analyses and prediction in model

Revision ID: 8565ff01dc67
Revises: 42b57befbbfe
Create Date: 2025-12-10 16:44:29.404707

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "8565ff01dc67"
down_revision: Union[str, Sequence[str], None] = "42b57befbbfe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
