"""added anomaly table

Revision ID: b1681f39a192
Revises: fea28f6fceb8
Create Date: 2025-10-24 11:07:50.761128

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1681f39a192"
down_revision: Union[str, Sequence[str], None] = "fea28f6fceb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anomalies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("start_idx", sa.DateTime(), nullable=False),
        sa.Column("end_idx", sa.DateTime(), nullable=False),
        sa.Column("type", sa.Enum("point", "contextual", name="anomalytype"), nullable=False),
        sa.Column("validated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("anomalies")
    # ### end Alembic commands ###
